// src/raid/sprites/classes/hammer.js
// Broad, squat heavy, 20×28, two-handed war hammer drawn in. Pure data — no imports (node-loadable).
// Chars: K outline, S skin, H hair, A armor, B dark, P pants, W grip, L hammer head, G gem.
// The skull sits 1 col right of the torso centre — the hammer side pulls the stance rightward.
// headAnchors target the visual face centre, not the headBox geometric centre (sword.js does the same).

const IDLE_A = [
  '....................',
  '....................',
  '....................',
  '....................',
  '.....KKKKKKKK.......',
  '....KHHHHHHHHK......',
  '....KHHHHHHHHK......',
  '....KHSSSSSSHK......',
  '....KSSKSSKSSK......',
  '....KSSSSSSSSK..KKK.',
  '....KSSSSSSSSK..KWK.',
  'KKAAAAAAAAAAAAKKKWK.',
  '.KAAKAAAGAAAAKAAKWK.',
  '.KAAKAAAAAAAAKAKSSK.',
  '.KAAKAAAAAAAAKAKSSK.',
  '.KSSKAAAAAAAAKKKKWK.',
  '.KKKKAAAAAAAAK..KWK.',
  '..KKBBBBBBBBKK..KWK.',
  '...KAAAAAAAAK...KWK.',
  '...KAAAAAAAAK...KWK.',
  '...KPPPKKPPPK...KWK.',
  '..KPPPK.KPPPK...KWK.',
  '..KPPPK.KPPPK...KWK.',
  '..KPPPK.KPPPK.KKKKKK',
  '.KKBBBK.KBBBK.KLLLLK',
  '.KBBBBK.KBBBBKKLLLLK',
  '.KBBBBK.KBBBBKKLLLLK',
  '.KBBBBK.KBBBBKKKKKKK',
];

// Breathing: left torso edge widens 1px, chest gem glints a row lower.
const IDLE_B_EDITS = {
  12: 'KKAAKAAAAAAAAKAAKWK.',
  13: 'KKAAKAAAGAAAAKAKSSK.',
};
const IDLE_B = IDLE_A.map((r, y) => IDLE_B_EDITS[y] ?? r);

// Wind-up: hammer hoisted overhead two-handed, arms up, torso coiled low.
const ATTACK_A = [
  '......KKKKKK........',
  '......KLLLLK........',
  '......KLLLLK........',
  '......KLLLLK........',
  '......KKKKKK........',
  '........KWK.........',
  '.......KSWSK........',
  '......KASWSAK.......',
  '.....KAAK.KAAK......',
  '....KAAKKKKKKKKAAK..',
  '...KAAKHHHHHHHHKAAK.',
  '...KAAKHHHHHHHHKAAK.',
  '...KAAKHSSSSSSHKAAK.',
  '...KAAKSSKSSKSSKAAK.',
  '....KAKSSSSSSSSKAK..',
  '.KKAAAAAAAAAAAAAAKK.',
  '..KAAAAAGAAAAAAK....',
  '..KAAAAAAAAAAAAK....',
  '..KKBBBBBBBBBBKK....',
  '...KAAAAAAAAAK......',
  '...KPPPKKPPPK.......',
  '..KPPPK.KPPPK.......',
  '..KPPPK.KPPPK.......',
  '..KPPPK.KPPPK.......',
  '..KPPPK.KPPPK.......',
  '.KKBBBK.KBBBK.......',
  '.KBBBBK.KBBBBK......',
  '.KBBBBK.KBBBBK......',
];

// Strike: bent forward, hammer slammed down in front — head lands around row 20.
const ATTACK_B = [
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '......KKKKKKKK......',
  '.....KHHHHHHHHK.....',
  '.....KHHHHHHHHK.....',
  '.....KHSSSSSSHK.....',
  '.....KSSKSSKSSK.....',
  '.....KSSSSSSSSK.....',
  '.....KSSSSSSSSK.....',
  '.KKAAAAAAAAAAAAKK...',
  '.KAAAAAAAAAAAAKSSK..',
  '.KAAKAAAGAAAAKKSSK..',
  '.KKKKAAAAAAAAKKKWK..',
  '...KBBBBBBBBK..KWK..',
  '...KPPPKKPPPK.KKKKKK',
  '..KPPPK.KPPPK.KLLLLK',
  '..KPPPK.KPPPK.KLLLLK',
  '.KPPPK..KPPPK.KLLLLK',
  '.KPPPK..KPPPK.KKKKKK',
  '.KPPPK..KPPPK.......',
  '.KPPPK..KPPPK.......',
  'KKBBBK..KBBBK.......',
  'KBBBBK..KBBBBK......',
  'KBBBBK..KBBBBK......',
];

// Exhausted: down on the back knee, both hands on the upright hammer.
const KNEEL = [
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '................KKK.',
  '......KKKKKKKK..KWK.',
  '.....KHHHHHHHHK.KWK.',
  '.....KHHHHHHHHK.KWK.',
  '.....KHSSSSSSHK.KWK.',
  '.....KSSKSSKSSK.KWK.',
  '.....KSSSSSSSSK.KSK.',
  '..KKKAAAAAAAAAAKKSK.',
  '.KAAKAAAGAAAAKAASSK.',
  '.KAAKAAAAAAAAKKKKWK.',
  '.KKKKBBBBBBBBK..KWK.',
  '...KAAAAAAAAK...KWK.',
  '...KPPPKKPPPK...KWK.',
  '..KPPPK.KPPPK...KWK.',
  '..KPPK..KPPPK...KWK.',
  '..KPPK..KPPPK...KWK.',
  '.KKPPK..KPPPK.KKKKKK',
  '.KBBBK..KPPPK.KLLLLK',
  '.KBBBK..KPPPK.KLLLLK',
  '.KBBBKK.KBBBBKKLLLLK',
  '..KKKK..KBBBBKKKKKKK',
];

// Knocked down: flat on the back, hammer dropped above him.
const DOWN = [
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '..KKKKK.............',
  '..KLLLK.............',
  '..KLLLKWWWWWWWW.....',
  '..KLLLK.............',
  '..KKKKK.............',
  '....................',
  '...KKKKKK...........',
  '..KHHHHHHKKKKKKKKK..',
  '.KHHHHHHHKAAAAAAABK.',
  '.KHSSSSSHKAAGAAAABPK',
  '.KSSKSSKSHKAAAAAABPK',
  '.KHSSSSSHKAAAAAABPPK',
  '..KKKKKKKKKKKKKKKKK.',
  '....................',
];

export default {
  poses: [IDLE_A, IDLE_B, ATTACK_A, ATTACK_B, KNEEL, DOWN],
  // Erase-box per pose for the avatar-headed variant (pixel coords, inclusive).
  headBoxes: [
    { x0: 4, y0: 0, x1: 14, y1: 10 },
    { x0: 4, y0: 0, x1: 14, y1: 10 },
    { x0: 6, y0: 9, x1: 15, y1: 14 },
    { x0: 5, y0: 3, x1: 14, y1: 12 },
    { x0: 5, y0: 8, x1: 14, y1: 13 },
    { x0: 1, y0: 19, x1: 9, y1: 26 },
  ],
  // [cx, cy] head-centre per pose, 20×28 pixel space.
  headAnchors: [
    [9, 7], [9, 7], [10.5, 11.5], [9.5, 9.5], [9.5, 10.5], [5, 23],
  ],
  // Hair overlay top-left per pose; null = no hair on this pose (lying down).
  hairAt: [[5, 3], [5, 3], [6, 8], [6, 5], [6, 7], null],
};
