// src/raid/sprites/classes/sword.js
// Balanced knight, 20×28, sword drawn in. Pure data — no imports (node-loadable).
// Chars: K outline, S skin, H hair, A armor, B dark, P pants, W grip, L blade, G gem.

const IDLE_A = [
  '....................',
  '.......KKKKK....L...',
  '......KHHHHHK..KLK..',
  '.....KHHHHHHHK.KLK..',
  '.....KHHHHHHHK.KLK..',
  '.....KHSSSSSHK.KLK..',
  '.....KSSKSSKSK.KLK..',
  '.....KSSSSSSSK.KLK..',
  '......KSSSSSK..KLK..',
  '.......KSSSK...KLK..',
  '.....KKAAAAAKK.KWK..',
  '....KAAAAAAAAAKKWK..',
  '...KAAKAAGAAKAAKSK..',
  '...KAAKAAAAAAKASSK..',
  '...KSSKAAAAAAKKSK...',
  '...KKKKBAAAABKKK....',
  '......KBBBBBBK......',
  '......KAAAAAAK......',
  '......KAAAAAAK......',
  '......KPPKKPPK......',
  '.....KPPK..KPPK.....',
  '.....KPPK..KPPK.....',
  '.....KPPK..KPPK.....',
  '.....KPPK..KPPK.....',
  '.....KPPK..KPPK.....',
  '....KKPPK..KPPKK....',
  '....KBBBK..KBBBK....',
  '...KKBBBK..KBBBKK...',
];

// Breathing: shoulders settle, chest gem glints a row higher.
const IDLE_B_EDITS = {
  11: '....KAAAAGAAAAKKWK..',
  12: '...KAAKAAAAAKAAKSK..',
};
const IDLE_B = IDLE_A.map((r, y) => IDLE_B_EDITS[y] ?? r);

// Wind-up: sword raised high behind the head, torso coiled.
const ATTACK_A = [
  '............KLK.....',
  '...........KLK......',
  '...........KLK......',
  '......KKKKK.KLK.....',
  '.....KHHHHHKKLK.....',
  '....KHHHHHHHKLK.....',
  '....KHHHHHHHKWK.....',
  '....KHSSSSSHKWK.....',
  '....KSSKSSKSKSK.....',
  '....KSSSSSSSKSK.....',
  '.....KSSSSSKKSK.....',
  '......KSSSKKASK.....',
  '....KKAAAAAKAAK.....',
  '...KAAAAAAAAAAK.....',
  '...KAAKAAGAAAAK.....',
  '...KSSKAAAAAAK......',
  '...KKKKBAAAABK......',
  '......KBBBBBBK......',
  '......KAAAAAAK......',
  '......KAAAAAAK......',
  '......KPPKKPPK......',
  '.....KPPK..KPPK.....',
  '.....KPPK..KPPK.....',
  '.....KPPK..KPPK.....',
  '.....KPPK..KPPK.....',
  '....KKPPK..KPPKK....',
  '....KBBBK..KBBBK....',
  '...KKBBBK..KBBBKK...',
];

// Strike: lunge right, sword thrust horizontal to the grid edge.
const ATTACK_B = [
  '....................',
  '....................',
  '....................',
  '....KKKKK...........',
  '...KHHHHHK..........',
  '..KHHHHHHHK.........',
  '..KHHHHHHHK.........',
  '..KHSSSSSHK.........',
  '..KSSKSSKSK.........',
  '..KSSSSSSSK.........',
  '...KSSSSSK..........',
  '....KSSSK...........',
  '..KKAAAAAKK.........',
  '.KAAAAAAAAAKKKKKK...',
  '.KAAKAAGAAASSWLLLLLL',
  '.KAAKAAAAAAKKKKKK...',
  '.KSSKAAAAAAK........',
  '.KKKKBAAAABK........',
  '....KBBBBBBK........',
  '....KAAAAAAK........',
  '....KAAAAKKK........',
  '....KPPKKPPK........',
  '...KPPK..KPPKK......',
  '...KPPK...KPPPK.....',
  '..KPPK.....KPPPK....',
  '..KPPK......KPPK....',
  '.KKBBBK.....KBBBKK..',
  '.KBBBBK.....KBBBBK..',
];

// Exhausted: on one knee, sword planted as a cane.
const KNEEL = [
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '.......KKKKK........',
  '......KHHHHHK..KLK..',
  '.....KHHHHHHHK.KLK..',
  '.....KHHHHHHHK.KLK..',
  '.....KHSSSSSHK.KLK..',
  '.....KSSKSSKSK.KLK..',
  '......KSSSSSK..KLK..',
  '.......KSSSK...KLK..',
  '.....KKAAAAAKK.KWK..',
  '....KAAAAAAAAAKKWK..',
  '...KAAKAAGAAAAKSSK..',
  '...KSSKAAAAAAAKSK...',
  '...KKKKBAAAAABKK....',
  '......KBBBBBBK......',
  '.....KAAAAAAAK......',
  '....KPPKAAAAPPK.....',
  '...KPPK.KPPPPPK.....',
  '...KPPK.KPPKPPK.....',
  '..KPPK..KPPKKPPK....',
  '..KPPK..KPPK.KPPK...',
  '.KKBBBKKKPPK..KBBK..',
  '.KBBBBKKBBBK..KBBK..',
  '....................',
];

// Knocked down: flat on the back, sword dropped above.
const DOWN = [
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '..LLLLLLW...........',
  '....................',
  '....KKKKK...........',
  '...KHHHHHKKKKKKKKK..',
  '..KHHHHHHKAAAAAAABK.',
  '..KHSSSSHKAAGAAAABPK',
  '..KSSKSSHKAAAAAABPPK',
  '..KHSSSSHKAAAAAABPK.',
  '...KKKKKKKKKKKKKKK..',
  '....................',
];

export default {
  poses: [IDLE_A, IDLE_B, ATTACK_A, ATTACK_B, KNEEL, DOWN],
  // Erase-box per pose for the avatar-headed variant (pixel coords, inclusive).
  headBoxes: [
    { x0: 4, y0: 0, x1: 14, y1: 9 },
    { x0: 4, y0: 0, x1: 14, y1: 9 },
    { x0: 3, y0: 3, x1: 11, y1: 12 },
    { x0: 1, y0: 3, x1: 10, y1: 11 },
    { x0: 4, y0: 5, x1: 13, y1: 12 },
    { x0: 1, y0: 20, x1: 8, y1: 26 },
  ],
  // [cx, cy] head-centre per pose, 20×28 pixel space.
  headAnchors: [
    [9, 4.5], [9, 4.5], [8, 7.5], [6, 7.5], [9, 9], [5, 23.5],
  ],
  // Hair overlay top-left per pose; null = no hair on this pose (e.g. lying down).
  hairAt: [[5, 0], [5, 0], [4, 2], [2, 2], [5, 4], null],
};
